"use client"
import Head from "next/head";
import Header from "@/components/Header";
import NavBar from "@/components/Navbar";
import WhatWeDo from "@/components/WhatWeDo";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Services from "@/components/Services";
import NeedUs from "@/components/NeedUs";
import Trusted from "@/components/Trusted";
import Connect from "@/components/Connect";
import Footer from "@/components/Footer";
import Preloader from "@/components/Preloader";
import { useEffect, useState } from "react";

export default function Home() {

  // --------------------preloader-------------------
  const [screenLoading, setScreenLoading] = useState(false);

  useEffect(() => {
    setScreenLoading(true);
    setTimeout(() => {
      setScreenLoading(false);
    }, 2500);
  }, []);
  return (
    <>
      <div className='overflow-x-hidden'>
        {screenLoading ? (
          <Preloader />
        ) : (
            <>
              <Head>
                <title>Fluff</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
              </Head>
              <main>
                <div className="mw_1920 mx-auto">
                  <NavBar />
                  <Header />
                  <WhatWeDo />
                  <Services />
                  <NeedUs />
                  <Trusted />
                  <Connect />
                </div>
                <Footer />
                {/* <Preloader /> */}
              </main>
            </>
        )
        }
      </div >
     
    </>
  );
}
